package p9;

//accessing parent class constructor without writing super()
//super keyword with args are not automatically generated

public class B extends A{
	B(){
		//ERROR b/c super keyword with args cannot be automatically generated by complier
		System.out.println("from B");
	}
	public static void main(String[] args) {
		new B();
	}
}
